POST http://localhost:1234/comments/693416f5985008f4614f1b82 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJuYW1lIjoiSmFjayBUb3JyYW5jZSIsImlkIjoiNjhmY2E3ZmI4M2MzOTVmZWQxNTAzYjdmIiwiaWF0IjoxNzY1MDE5MTQ3LCJleHAiOjE3NjUxOTE5NDd9.JjFzH1p0-uC0NDhiMakUyiyF13dAmXKV1Zn-NPhLB8A
Content-Type: application/json

{
  "text": "efwvrewvggvregvrfvgdsergvfawrgfvwargfv",
  "rating": 4
}

###
GET http://localhost:1234/comments/693416f5985008f4614f1b82 HTTP/1.1
